### ISSUE TITLE
Optimize Mongo2go Integration tests.

### ISSUE THREAD

**Issue by dacanizares** [equilaterus/Vortex#21]

**Comment by pipecaniza** [comment]
Static Mongo runner nor MongoDbFixture worked. It does some tests correctly, then pauses on an infinite loop.

**Comment by dacanizares** [comment]
After updating Mongo2Go to its latest version, static MongoRunner seems to work correctly. https://github.com/equilaterus/Vortex/blob/dev/test/Vortex.Saturn.Data.MongoDB.FunctionalTests/MongoDbTests.cs

We will keep investigating.

**Comment by dacanizares** [comment]
Discarded
