### ISSUE TITLE
Add BenchmarkDotNet tests

### ISSUE THREAD

**Issue by pipecaniza** [equilaterus/Vortex#44]
https://github.com/dotnet/BenchmarkDotNet

**Comment by dacanizares** [comment]
Idea is to add more experiments to get accurate performance impact results. We will keep current ones, as they're lighter so we can use them easily from day to day tasks.

**Comment by dacanizares** [comment]
Discarded

**Comment by devharf2310** [comment]
Why did you discard these benchmarking implementation?

**Comment by dacanizares** [comment]
On the new approach there's no overhead (except from the use of functional structures on C#). Previously we had a complete system based on Reflection so we needed to optimize it.
